### ISSUE TITLE
Display pop-up when user click on "Download"

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/slicer-extensions-webapp#13]
When browsing extensions in a regular web browser, clicking on the "Download" button should display an information box with the following info:

```
The preferred way to install extension is to open the extension manager directly from the Slicer application and click on the "Install" button.

Alternatively, the selected extension archive can directly be downloaded using the following link and later installed from file:

  29312_AnglePlanesExtension_macosx_amd64_1bef6f3.tar.gz

```

Related issues:
* https://github.com/Slicer/Slicer/issues/5863

_Originally posted by @jcfr in https://github.com/Slicer/slicer.org/issues/46#issuecomment-669941163_

**Comment by lassoan** [comment]
Since the extensions manager often does not work behind proxy servers, corporate/hospital firewalls, and when custom SSL certificates are used, downloading from the website should be considered a normal use case. Therefore no popups should be displayed (they would make the already slightly annoyed users more angry), but Download button should download the extension package directly. Thank you!
