### ISSUE TITLE
Half of the extensions are missing from the extensions list

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/slicer-extensions-webapp#44]
Only 86 extensions are listed in the new extensions manager for the last nightly build (https://extensions.slicer.org/catalog/All/30117/win), so a large part of the extensions are missing.

For example, SegmentEditorExtraEffects extension is built successfully on all platforms, 

https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-08-12&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ExtraEffects

The package can be downloaded from midas, for example:

http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&name=30117-win-amd64-SegmentEditorExtraEffects-git86ccd9f-2021-06-29.zip&checksum=93fb6b9c39fdadbaf4c06529af8f4e68

Yet, the extension does not appear in the new Extensions Manager:

**Comment by jcfr** [comment]
Thanks for the detailed report.

## Few observations

* Extension `SegmentEditorExtraEffects` has been uploaded with `30102`  . See hhttps://extensions.slicer.org/catalog/All/30102/win?q=ExtraEffects
* Extension `SegmentEditorExtraEffects` has *not* been uploaded with the next preview `30110`. See https://extensions.slicer.org/catalog/All/30110/win?q=ExtraEffects 
* Between `30102` (https://github.com/Slicer/Slicer/commit/5520659c00eccc73641a7e61b6c649dae35d58e6) and `30110` (https://github.com/Slicer/Slicer/commit/489a919a321c7911dc4918), the following changes have been integrated to [Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake](https://github.com/Slicer/Slicer/blob/master/Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake)

    | commit | title | revision | status |
    |--|--|--|--|
    | https://github.com/Slicer/Slicer/commit/5520659c00eccc73641a7e61b6c649dae35d58e6 |  ENH: Ensure contributors metadata is published with extension packages | 30102 | :heavy_check_mark: |
    | https://github.com/Slicer/Slicer/commit/8f33d93e8c826b83267b637910fd3bebb026dcf4 | ENH: Ensure dependency metadata is published with extension packages | 30105 | :negative_squared_cross_mark: |
    | https://github.com/Slicer/Slicer/commit/23e8fb730f5e27fb759c7fbfffa4454c752db089 | COMP: Fix upload of extension with semi-colon in description metadata | 30106 | :negative_squared_cross_mark: |
    | https://github.com/Slicer/Slicer/commit/23e8fb730f5e27fb759c7fbfffa4454c752db089 | COMP: Report Midas_v1 extension package upload failures as warnings | 30110 | :negative_squared_cross_mark: |

## Analysis

I suspect the change introduced in https://github.com/Slicer/Slicer/commit/8f33d93e8c826b83267b637910fd3bebb026dcf4 is the culprit:

```diff
- file(WRITE ${script_args_file} ${script_arg_list})
+ file(WRITE ${script_args_file} "${script_arg_list}")
``` 

See https://github.com/Slicer/Slicer/blame/1a692bf36e9c99c47661fbf5fdba0fd3c3e72f95/Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake#L159

Indeed, after this change, the `;` in any field were not stripped and this caused `execute_process` to fail. Commit https://github.com/Slicer/Slicer/commit/23e8fb730f5e27fb759c7fbfffa4454c752db089 attempted to fix the issue but this does not seem sufficient.

```diff
- --desc ${EXTENSION_DESCRIPTION}
+ --desc "${EXTENSION_DESCRIPTION}"
```

See https://github.com/Slicer/Slicer/blame/1a692bf36e9c99c47661fbf5fdba0fd3c3e72f95/Extensions/CMake/SlicerExtensionPackageAndUploadTarget.cmake#L346

## Conclusion

* We likely need to escape with double quotes all parameter passed to `SLICER_EXTENSION_MANAGER_CLIENT_EXECUTABLE`

* To ensure failures are reported on the dashboard, we need to use `FATAL_ERROR` instead of `STATUS`. Using `STATUS` was sensible when upload to the new backend were optional but now we need to avoid false positive and have upload error reported on the dashboard.

**Comment by jcfr** [comment]
Content of `slicer_extension_server_upload_errors.txt`

```
$ cat slicer_extension_server_upload_errors.txt
Usage: slicer_package_manager_client extension upload [OPTIONS] APP_NAME
                                                      FILEPATH
Try 'slicer_package_manager_client extension upload -h' for help.

Error: Got unexpected extra argument ( SPL, BWH), Andrey Fedorov (SPL, BWH))
```

This is explained because there is a `;` to set `EXTENSION_CONTRIBUTORS` in [SlicerSegmentEditorExtraEffects/CMakeLists.txt](https://github.com/lassoan/SlicerSegmentEditorExtraEffects/blob/86ccd9f223c0eddef913f7977ceeac67e84934ce/CMakeLists.txt#L9)

**Comment by jcfr** [comment]
Applying the fix directly on the linux factory (aka metroplex) allows to upload the extension.
See https://extensions.slicer.org/catalog/All/30119/linux?q=ExtraEffects

**Comment by lassoan** [comment]
Awesome! Thank you for the quick fix.
